curl --output KPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KPvK.rtbw
curl --output KPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KPvK.rtbz
curl --output KNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNvK.rtbw
curl --output KNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNvK.rtbz
curl --output KBvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBvK.rtbw
curl --output KBvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBvK.rtbz
curl --output KRvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRvK.rtbw
curl --output KRvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRvK.rtbz
curl --output KQvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQvK.rtbw
curl --output KQvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQvK.rtbz
curl --output KPvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KPvKP.rtbw
curl --output KPvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KPvKP.rtbz
curl --output KNvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNvKP.rtbw
curl --output KNvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNvKP.rtbz
curl --output KNvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNvKN.rtbw
curl --output KNvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNvKN.rtbz
curl --output KBvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBvKP.rtbw
curl --output KBvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBvKP.rtbz
curl --output KBvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBvKN.rtbw
curl --output KBvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBvKN.rtbz
curl --output KBvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBvKB.rtbw
curl --output KBvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBvKB.rtbz
curl --output KRvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRvKP.rtbw
curl --output KRvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRvKP.rtbz
curl --output KRvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRvKN.rtbw
curl --output KRvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRvKN.rtbz
curl --output KRvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRvKB.rtbw
curl --output KRvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRvKB.rtbz
curl --output KRvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRvKR.rtbw
curl --output KRvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRvKR.rtbz
curl --output KQvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQvKP.rtbw
curl --output KQvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQvKP.rtbz
curl --output KQvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQvKN.rtbw
curl --output KQvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQvKN.rtbz
curl --output KQvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQvKB.rtbw
curl --output KQvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQvKB.rtbz
curl --output KQvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQvKR.rtbw
curl --output KQvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQvKR.rtbz
curl --output KQvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQvKQ.rtbw
curl --output KQvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQvKQ.rtbz
curl --output KPPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KPPvK.rtbw
curl --output KPPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KPPvK.rtbz
curl --output KNPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNPvK.rtbw
curl --output KNPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNPvK.rtbz
curl --output KNNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNNvK.rtbw
curl --output KNNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNNvK.rtbz
curl --output KBPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBPvK.rtbw
curl --output KBPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBPvK.rtbz
curl --output KBNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBNvK.rtbw
curl --output KBNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBNvK.rtbz
curl --output KBBvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBBvK.rtbw
curl --output KBBvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBBvK.rtbz
curl --output KRPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRPvK.rtbw
curl --output KRPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRPvK.rtbz
curl --output KRNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRNvK.rtbw
curl --output KRNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRNvK.rtbz
curl --output KRBvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRBvK.rtbw
curl --output KRBvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRBvK.rtbz
curl --output KRRvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRRvK.rtbw
curl --output KRRvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRRvK.rtbz
curl --output KQPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQPvK.rtbw
curl --output KQPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQPvK.rtbz
curl --output KQNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQNvK.rtbw
curl --output KQNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQNvK.rtbz
curl --output KQBvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQBvK.rtbw
curl --output KQBvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQBvK.rtbz
curl --output KQRvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQRvK.rtbw
curl --output KQRvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQRvK.rtbz
curl --output KQQvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQQvK.rtbw
curl --output KQQvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQQvK.rtbz
curl --output KPPvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KPPvKP.rtbw
curl --output KPPvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KPPvKP.rtbz
curl --output KPPvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KPPvKN.rtbw
curl --output KPPvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KPPvKN.rtbz
curl --output KPPvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KPPvKB.rtbw
curl --output KPPvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KPPvKB.rtbz
curl --output KPPvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KPPvKR.rtbw
curl --output KPPvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KPPvKR.rtbz
curl --output KPPvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KPPvKQ.rtbw
curl --output KPPvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KPPvKQ.rtbz
curl --output KNPvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNPvKP.rtbw
curl --output KNPvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNPvKP.rtbz
curl --output KNPvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNPvKN.rtbw
curl --output KNPvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNPvKN.rtbz
curl --output KNPvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNPvKB.rtbw
curl --output KNPvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNPvKB.rtbz
curl --output KNPvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNPvKR.rtbw
curl --output KNPvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNPvKR.rtbz
curl --output KNPvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNPvKQ.rtbw
curl --output KNPvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNPvKQ.rtbz
curl --output KNNvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNNvKP.rtbw
curl --output KNNvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNNvKP.rtbz
curl --output KNNvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNNvKN.rtbw
curl --output KNNvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNNvKN.rtbz
curl --output KNNvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNNvKB.rtbw
curl --output KNNvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNNvKB.rtbz
curl --output KNNvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNNvKR.rtbw
curl --output KNNvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNNvKR.rtbz
curl --output KNNvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNNvKQ.rtbw
curl --output KNNvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNNvKQ.rtbz
curl --output KBPvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBPvKP.rtbw
curl --output KBPvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBPvKP.rtbz
curl --output KBPvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBPvKN.rtbw
curl --output KBPvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBPvKN.rtbz
curl --output KBPvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBPvKB.rtbw
curl --output KBPvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBPvKB.rtbz
curl --output KBPvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBPvKR.rtbw
curl --output KBPvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBPvKR.rtbz
curl --output KBPvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBPvKQ.rtbw
curl --output KBPvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBPvKQ.rtbz
curl --output KBNvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBNvKP.rtbw
curl --output KBNvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBNvKP.rtbz
curl --output KBNvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBNvKN.rtbw
curl --output KBNvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBNvKN.rtbz
curl --output KBNvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBNvKB.rtbw
curl --output KBNvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBNvKB.rtbz
curl --output KBNvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBNvKR.rtbw
curl --output KBNvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBNvKR.rtbz
curl --output KBNvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBNvKQ.rtbw
curl --output KBNvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBNvKQ.rtbz
curl --output KBBvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBBvKP.rtbw
curl --output KBBvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBBvKP.rtbz
curl --output KBBvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBBvKN.rtbw
curl --output KBBvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBBvKN.rtbz
curl --output KBBvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBBvKB.rtbw
curl --output KBBvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBBvKB.rtbz
curl --output KBBvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBBvKR.rtbw
curl --output KBBvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBBvKR.rtbz
curl --output KBBvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBBvKQ.rtbw
curl --output KBBvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBBvKQ.rtbz
curl --output KRPvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRPvKP.rtbw
curl --output KRPvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRPvKP.rtbz
curl --output KRPvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRPvKN.rtbw
curl --output KRPvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRPvKN.rtbz
curl --output KRPvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRPvKB.rtbw
curl --output KRPvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRPvKB.rtbz
curl --output KRPvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRPvKR.rtbw
curl --output KRPvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRPvKR.rtbz
curl --output KRPvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRPvKQ.rtbw
curl --output KRPvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRPvKQ.rtbz
curl --output KRNvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRNvKP.rtbw
curl --output KRNvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRNvKP.rtbz
curl --output KRNvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRNvKN.rtbw
curl --output KRNvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRNvKN.rtbz
curl --output KRNvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRNvKB.rtbw
curl --output KRNvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRNvKB.rtbz
curl --output KRNvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRNvKR.rtbw
curl --output KRNvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRNvKR.rtbz
curl --output KRNvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRNvKQ.rtbw
curl --output KRNvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRNvKQ.rtbz
curl --output KRBvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRBvKP.rtbw
curl --output KRBvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRBvKP.rtbz
curl --output KRBvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRBvKN.rtbw
curl --output KRBvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRBvKN.rtbz
curl --output KRBvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRBvKB.rtbw
curl --output KRBvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRBvKB.rtbz
curl --output KRBvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRBvKR.rtbw
curl --output KRBvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRBvKR.rtbz
curl --output KRBvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRBvKQ.rtbw
curl --output KRBvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRBvKQ.rtbz
curl --output KRRvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRRvKP.rtbw
curl --output KRRvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRRvKP.rtbz
curl --output KRRvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRRvKN.rtbw
curl --output KRRvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRRvKN.rtbz
curl --output KRRvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRRvKB.rtbw
curl --output KRRvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRRvKB.rtbz
curl --output KRRvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRRvKR.rtbw
curl --output KRRvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRRvKR.rtbz
curl --output KRRvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRRvKQ.rtbw
curl --output KRRvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRRvKQ.rtbz
curl --output KQPvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQPvKP.rtbw
curl --output KQPvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQPvKP.rtbz
curl --output KQPvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQPvKN.rtbw
curl --output KQPvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQPvKN.rtbz
curl --output KQPvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQPvKB.rtbw
curl --output KQPvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQPvKB.rtbz
curl --output KQPvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQPvKR.rtbw
curl --output KQPvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQPvKR.rtbz
curl --output KQPvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQPvKQ.rtbw
curl --output KQPvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQPvKQ.rtbz
curl --output KQNvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQNvKP.rtbw
curl --output KQNvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQNvKP.rtbz
curl --output KQNvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQNvKN.rtbw
curl --output KQNvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQNvKN.rtbz
curl --output KQNvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQNvKB.rtbw
curl --output KQNvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQNvKB.rtbz
curl --output KQNvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQNvKR.rtbw
curl --output KQNvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQNvKR.rtbz
curl --output KQNvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQNvKQ.rtbw
curl --output KQNvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQNvKQ.rtbz
curl --output KQBvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQBvKP.rtbw
curl --output KQBvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQBvKP.rtbz
curl --output KQBvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQBvKN.rtbw
curl --output KQBvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQBvKN.rtbz
curl --output KQBvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQBvKB.rtbw
curl --output KQBvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQBvKB.rtbz
curl --output KQBvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQBvKR.rtbw
curl --output KQBvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQBvKR.rtbz
curl --output KQBvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQBvKQ.rtbw
curl --output KQBvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQBvKQ.rtbz
curl --output KQRvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQRvKP.rtbw
curl --output KQRvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQRvKP.rtbz
curl --output KQRvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQRvKN.rtbw
curl --output KQRvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQRvKN.rtbz
curl --output KQRvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQRvKB.rtbw
curl --output KQRvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQRvKB.rtbz
curl --output KQRvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQRvKR.rtbw
curl --output KQRvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQRvKR.rtbz
curl --output KQRvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQRvKQ.rtbw
curl --output KQRvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQRvKQ.rtbz
curl --output KQQvKP.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQQvKP.rtbw
curl --output KQQvKP.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQQvKP.rtbz
curl --output KQQvKN.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQQvKN.rtbw
curl --output KQQvKN.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQQvKN.rtbz
curl --output KQQvKB.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQQvKB.rtbw
curl --output KQQvKB.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQQvKB.rtbz
curl --output KQQvKR.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQQvKR.rtbw
curl --output KQQvKR.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQQvKR.rtbz
curl --output KQQvKQ.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQQvKQ.rtbw
curl --output KQQvKQ.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQQvKQ.rtbz
curl --output KPPPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KPPPvK.rtbw
curl --output KPPPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KPPPvK.rtbz
curl --output KNPPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNPPvK.rtbw
curl --output KNPPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNPPvK.rtbz
curl --output KNNPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNNPvK.rtbw
curl --output KNNPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNNPvK.rtbz
curl --output KNNNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KNNNvK.rtbw
curl --output KNNNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KNNNvK.rtbz
curl --output KBPPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBPPvK.rtbw
curl --output KBPPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBPPvK.rtbz
curl --output KBNPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBNPvK.rtbw
curl --output KBNPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBNPvK.rtbz
curl --output KBNNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBNNvK.rtbw
curl --output KBNNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBNNvK.rtbz
curl --output KBBPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBBPvK.rtbw
curl --output KBBPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBBPvK.rtbz
curl --output KBBNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBBNvK.rtbw
curl --output KBBNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBBNvK.rtbz
curl --output KBBBvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KBBBvK.rtbw
curl --output KBBBvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KBBBvK.rtbz
curl --output KRPPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRPPvK.rtbw
curl --output KRPPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRPPvK.rtbz
curl --output KRNPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRNPvK.rtbw
curl --output KRNPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRNPvK.rtbz
curl --output KRNNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRNNvK.rtbw
curl --output KRNNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRNNvK.rtbz
curl --output KRBPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRBPvK.rtbw
curl --output KRBPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRBPvK.rtbz
curl --output KRBNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRBNvK.rtbw
curl --output KRBNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRBNvK.rtbz
curl --output KRBBvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRBBvK.rtbw
curl --output KRBBvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRBBvK.rtbz
curl --output KRRPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRRPvK.rtbw
curl --output KRRPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRRPvK.rtbz
curl --output KRRNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRRNvK.rtbw
curl --output KRRNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRRNvK.rtbz
curl --output KRRBvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRRBvK.rtbw
curl --output KRRBvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRRBvK.rtbz
curl --output KRRRvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KRRRvK.rtbw
curl --output KRRRvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KRRRvK.rtbz
curl --output KQPPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQPPvK.rtbw
curl --output KQPPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQPPvK.rtbz
curl --output KQNPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQNPvK.rtbw
curl --output KQNPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQNPvK.rtbz
curl --output KQNNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQNNvK.rtbw
curl --output KQNNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQNNvK.rtbz
curl --output KQBPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQBPvK.rtbw
curl --output KQBPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQBPvK.rtbz
curl --output KQBNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQBNvK.rtbw
curl --output KQBNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQBNvK.rtbz
curl --output KQBBvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQBBvK.rtbw
curl --output KQBBvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQBBvK.rtbz
curl --output KQRPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQRPvK.rtbw
curl --output KQRPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQRPvK.rtbz
curl --output KQRNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQRNvK.rtbw
curl --output KQRNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQRNvK.rtbz
curl --output KQRBvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQRBvK.rtbw
curl --output KQRBvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQRBvK.rtbz
curl --output KQRRvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQRRvK.rtbw
curl --output KQRRvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQRRvK.rtbz
curl --output KQQPvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQQPvK.rtbw
curl --output KQQPvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQQPvK.rtbz
curl --output KQQNvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQQNvK.rtbw
curl --output KQQNvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQQNvK.rtbz
curl --output KQQBvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQQBvK.rtbw
curl --output KQQBvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQQBvK.rtbz
curl --output KQQRvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQQRvK.rtbw
curl --output KQQRvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQQRvK.rtbz
curl --output KQQQvK.rtbw http://tablebase.sesse.net/syzygy/3-4-5/KQQQvK.rtbw
curl --output KQQQvK.rtbz http://tablebase.sesse.net/syzygy/3-4-5/KQQQvK.rtbz
